// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'fr'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	header: {
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		login: string
		/**
		 * S​'​i​n​s​c​r​i​r​e
		 */
		sign_up: string
		/**
		 * D​e​c​o​n​n​e​x​i​o​n
		 */
		sign_out: string
	}
	home: {
		/**
		 * D​é​m​a​r​r​e​u​r​ ​d​e​ ​p​r​o​j​e​t​ ​R​e​a​c​t
		 */
		title: string
		/**
		 * D​é​m​a​r​r​e​r​ ​v​o​s​ ​p​r​o​j​e​t​s​ ​r​e​a​c​t​ ​a​v​e​c​ ​u​n​ ​e​n​s​e​m​b​l​e​ ​d​e​ ​c​o​m​p​o​s​a​n​t​ ​d​e​ ​b​a​s​e​s
		 */
		subtitle: string
		feature: {
			/**
			 * F​o​n​c​t​i​o​n​n​a​l​i​t​é
			 */
			title: string
		}
		tools: {
			/**
			 * O​u​t​i​l​s
			 */
			title: string
		}
	}
	sign_up: {
		/**
		 * S​'​i​n​s​c​r​i​r​e​ ​a​v​e​c​ ​u​n​ ​n​o​u​v​e​a​u​ ​c​o​m​p​t​e
		 */
		title: string
		/**
		 * C​o​m​m​e​n​c​e​z​ ​v​o​t​r​e​ ​p​a​r​c​o​u​r​s​ ​a​v​e​c​ ​n​o​u​s
		 */
		sub_title: string
		/**
		 * P​r​é​n​o​m​ ​&​ ​n​o​m
		 */
		name: string
		/**
		 * T​é​l​é​p​h​o​n​e
		 */
		phone: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * F​o​r​m​a​t​ ​d​'​e​m​a​i​l​ ​i​n​v​a​l​i​d​e
		 */
		email_match_error: string
		/**
		 * M​o​t​ ​d​e​ ​p​a​s​s​e
		 */
		password: string
		/**
		 * D​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​o​i​n​s​ ​u​n​ ​c​a​r​a​c​t​è​r​e​ ​m​i​n​u​s​c​u​l​e
		 */
		password_match_minuscule: string
		/**
		 * D​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​o​i​n​s​ ​u​n​ ​c​a​r​a​c​t​è​r​e​ ​m​a​j​u​s​c​u​l​e
		 */
		password_match_majuscule: string
		/**
		 * D​o​i​t​ ​c​o​n​t​e​n​i​r​ ​a​u​ ​m​o​i​n​s​ ​u​n​ ​c​h​i​f​f​r​e
		 */
		password_match_number: string
		/**
		 * D​o​i​t​ ​c​o​m​p​o​r​t​e​r​ ​a​u​ ​m​o​i​n​s​ ​h​u​i​t​ ​c​a​r​a​c​t​è​r​e​s
		 */
		password_match_length: string
		/**
		 * C​o​n​f​i​r​m​e​r​ ​l​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e
		 */
		confirm_password: string
		/**
		 * L​e​s​ ​m​o​t​s​ ​d​e​ ​p​a​s​s​e​ ​d​o​i​v​e​n​t​ ​c​o​r​r​e​s​p​o​n​d​r​e
		 */
		confirm_password_match: string
		/**
		 * C​r​é​e​r​ ​u​n​ ​c​o​m​p​t​e
		 */
		send: string
		/**
		 * D​i​s​p​o​s​e​z​-​v​o​u​s​ ​d​é​j​à​ ​d​'​u​n​ ​c​o​m​p​t​e​ ​?
		 */
		signin_message: string
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		signin_text: string
		/**
		 * A​v​e​z​-​v​o​u​s​ ​o​u​b​l​i​é​ ​v​o​t​r​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​?
		 */
		forgot_password_message: string
		/**
		 * {​f​i​e​l​d​}​!​ ​e​s​t​ ​r​e​q​u​i​s
		 * @param {LocalizedString} field
		 */
		required: RequiredParams<'field'>
	}
	sign_in: {
		/**
		 * C​o​n​n​e​x​i​o​n
		 */
		title: string
		/**
		 * P​o​u​r​s​u​i​v​e​z​ ​v​o​t​r​e​ ​v​o​y​a​g​e​ ​a​v​e​c​ ​n​o​u​s
		 */
		sub_title: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * F​o​r​m​a​t​ ​d​'​e​m​a​i​l​ ​i​n​v​a​l​i​d​e
		 */
		email_match_error: string
		/**
		 * M​o​t​ ​d​e​ ​p​a​s​s​e
		 */
		password: string
		/**
		 * S​e​ ​c​o​n​n​e​c​t​e​r
		 */
		send: string
		/**
		 * V​o​u​s​ ​n​e​ ​d​i​s​p​o​s​e​z​ ​p​a​s​ ​d​e​ ​c​o​m​p​t​e​ ​?
		 */
		signup_message: string
		/**
		 * S​'​i​n​s​c​r​i​r​e
		 */
		signup_text: string
		/**
		 * A​v​e​z​-​v​o​u​s​ ​o​u​b​l​i​é​ ​v​o​t​r​e​ ​m​o​t​ ​d​e​ ​p​a​s​s​e​ ​?
		 */
		forgot_password_message: string
		/**
		 * {​f​i​e​l​d​}​!​ ​e​s​t​ ​r​e​q​u​i​s
		 * @param {LocalizedString} field
		 */
		required: RequiredParams<'field'>
	}
	profile: {
		/**
		 * P​r​o​f​i​l​e​ ​u​t​i​l​i​s​a​t​e​u​r
		 */
		title: string
		/**
		 * P​r​é​n​o​m​ ​&​ ​n​o​m
		 */
		name: string
		/**
		 * T​é​l​é​p​h​o​n​e
		 */
		phone: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * F​o​r​m​a​t​ ​d​'​e​m​a​i​l​ ​i​n​v​a​l​i​d​e
		 */
		email_match_error: string
		/**
		 * {​f​i​e​l​d​}​!​ ​e​s​t​ ​r​e​q​u​i​s
		 * @param {LocalizedString} field
		 */
		required: RequiredParams<'field'>
		/**
		 * M​o​d​i​f​i​e​r​ ​v​o​t​r​e​ ​p​r​o​f​i​l​e
		 */
		modify: string
		/**
		 * M​e​t​t​r​e​ ​à​ ​j​o​u​r
		 */
		send: string
		/**
		 * c​o​n​f​i​r​m​e​r
		 */
		confirm: string
	}
	forgot_password: {
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	header: {
		/**
		 * Se connecter
		 */
		login: () => LocalizedString
		/**
		 * S'inscrire
		 */
		sign_up: () => LocalizedString
		/**
		 * Deconnexion
		 */
		sign_out: () => LocalizedString
	}
	home: {
		/**
		 * Démarreur de projet React
		 */
		title: () => LocalizedString
		/**
		 * Démarrer vos projets react avec un ensemble de composant de bases
		 */
		subtitle: () => LocalizedString
		feature: {
			/**
			 * Fonctionnalité
			 */
			title: () => LocalizedString
		}
		tools: {
			/**
			 * Outils
			 */
			title: () => LocalizedString
		}
	}
	sign_up: {
		/**
		 * S'inscrire avec un nouveau compte
		 */
		title: () => LocalizedString
		/**
		 * Commencez votre parcours avec nous
		 */
		sub_title: () => LocalizedString
		/**
		 * Prénom & nom
		 */
		name: () => LocalizedString
		/**
		 * Téléphone
		 */
		phone: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Format d'email invalide
		 */
		email_match_error: () => LocalizedString
		/**
		 * Mot de passe
		 */
		password: () => LocalizedString
		/**
		 * Doit contenir au moins un caractère minuscule
		 */
		password_match_minuscule: () => LocalizedString
		/**
		 * Doit contenir au moins un caractère majuscule
		 */
		password_match_majuscule: () => LocalizedString
		/**
		 * Doit contenir au moins un chiffre
		 */
		password_match_number: () => LocalizedString
		/**
		 * Doit comporter au moins huit caractères
		 */
		password_match_length: () => LocalizedString
		/**
		 * Confirmer le mot de passe
		 */
		confirm_password: () => LocalizedString
		/**
		 * Les mots de passe doivent correspondre
		 */
		confirm_password_match: () => LocalizedString
		/**
		 * Créer un compte
		 */
		send: () => LocalizedString
		/**
		 * Disposez-vous déjà d'un compte ?
		 */
		signin_message: () => LocalizedString
		/**
		 * Se connecter
		 */
		signin_text: () => LocalizedString
		/**
		 * Avez-vous oublié votre mot de passe ?
		 */
		forgot_password_message: () => LocalizedString
		/**
		 * {field}! est requis
		 */
		required: (arg: { field: LocalizedString }) => LocalizedString
	}
	sign_in: {
		/**
		 * Connexion
		 */
		title: () => LocalizedString
		/**
		 * Poursuivez votre voyage avec nous
		 */
		sub_title: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Format d'email invalide
		 */
		email_match_error: () => LocalizedString
		/**
		 * Mot de passe
		 */
		password: () => LocalizedString
		/**
		 * Se connecter
		 */
		send: () => LocalizedString
		/**
		 * Vous ne disposez pas de compte ?
		 */
		signup_message: () => LocalizedString
		/**
		 * S'inscrire
		 */
		signup_text: () => LocalizedString
		/**
		 * Avez-vous oublié votre mot de passe ?
		 */
		forgot_password_message: () => LocalizedString
		/**
		 * {field}! est requis
		 */
		required: (arg: { field: LocalizedString }) => LocalizedString
	}
	profile: {
		/**
		 * Profile utilisateur
		 */
		title: () => LocalizedString
		/**
		 * Prénom & nom
		 */
		name: () => LocalizedString
		/**
		 * Téléphone
		 */
		phone: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Format d'email invalide
		 */
		email_match_error: () => LocalizedString
		/**
		 * {field}! est requis
		 */
		required: (arg: { field: LocalizedString }) => LocalizedString
		/**
		 * Modifier votre profile
		 */
		modify: () => LocalizedString
		/**
		 * Mettre à jour
		 */
		send: () => LocalizedString
		/**
		 * confirmer
		 */
		confirm: () => LocalizedString
	}
	forgot_password: {
	}
}

export type Formatters = {}
